# SPDX-FileCopyrightText: 2026 Bruno Pacheco (https://bruno.pacheco.lu|brunopacheco1@yahoo.com)
#
# SPDX-License-Identifier: Apache-2.0

project:
  type: book
  render:
    - docs/

profile:
  default: en

book:
  title: "Ma Quetelye Quenya?"
  author: "Bruno Pacheco"
  date: "18/04/2026"
  url: "https://ma-quetelye-quenya.tolkien.lu"

bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
