# SPDX-FileCopyrightText: 2026 Bruno Pacheco (https://bruno.pacheco.lu|brunopacheco1@yahoo.com)
#
# SPDX-License-Identifier: Apache-2.0
project:
  output-dir: _book/pt
book:
  language: pt
  chapters:
    - index.qmd
    - docs/pt/toc.qmd
    - docs/carince_1.qmd
    - docs/carince_2.qmd
    - docs/carince_3.qmd
    - docs/carince_4.qmd
    - docs/carince_5.qmd
    - docs/carince_6.qmd
    - docs/pt/neologisms.qmd
    - docs/cariquettar.qmd
