# SPDX-FileCopyrightText: 2026 Bruno Pacheco (https://bruno.pacheco.lu|brunopacheco1@yahoo.com)
#
# SPDX-License-Identifier: Apache-2.0

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [closed]
  workflow_dispatch:

name: Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      is_release: ${{ steps.version.outputs.is_release }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Determine Version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == 'pull_request' && "${{ github.event.pull_request.merged }}" == 'true' && "${{ contains(github.event.pull_request.labels.*.name, 'release') }}" == 'true' ]]; then
            TITLE="${{ github.event.pull_request.title }}"
            VERSION=${TITLE#Release }
            
            # Ensure version starts with v
            if [[ $VERSION != v* ]]; then
              VERSION="v$VERSION"
            fi
            
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Push Tag
        if: steps.version.outputs.is_release == 'true' && github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Install TinyTeX
        run: quarto install tinytex
      - name: Build documentation
        run: |
          quarto render --profile en
          quarto render --profile pt
      - name: Prepare Release Artifacts
        if: steps.version.outputs.is_release == 'true'
        run: |
          mkdir -p release_artifacts
          VERSION="${{ steps.version.outputs.version }}"
          ls -R _book
          cp _book/en/ma-quetelye-quenya.pdf release_artifacts/ma-quetelye-quenya-en-${VERSION}.pdf
          cp _book/en/ma-quetelye-quenya.epub release_artifacts/ma-quetelye-quenya-en-${VERSION}.epub
          cp _book/pt/ma-quetelye-quenya.pdf release_artifacts/ma-quetelye-quenya-pt-${VERSION}.pdf
          cp _book/pt/ma-quetelye-quenya.epub release_artifacts/ma-quetelye-quenya-pt-${VERSION}.epub
      - name: Upload release artifacts
        if: steps.version.outputs.is_release == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: book-artifacts
          path: release_artifacts/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./_book/en

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.is_release == 'true'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

  release:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.is_release == 'true'
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: book-artifacts
          path: release_artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.version }}
          generate_release_notes: true
          files: release_artifacts/*
